<?php
/**
 * Plugin Name: Topic Tree GPT
 * Plugin URI: https://yourwebsite.com
 * Description: Summarize and group WordPress posts and pages using GPT-4.
 * Version: 5.6.1
 * Author: Anoop, Navkaran, Mehakdeep, Jaskirat
 * Author URI: https://yourwebsite.com
 * License: GPL2
 */

if (!defined('ABSPATH')) {
    exit;
}

//ANCHOR this includes the other two php files to utilize their functions
require_once plugin_dir_path(__FILE__) . 'helpers.php';
require_once plugin_dir_path(__FILE__) . 'summarization.php';

//ANCHOR - this controls the menus for and by the plugin in the admin sidebar in WordPress
function topic_tree_add_admin_menus()
{
    add_menu_page(
        'Topic Tree Analysis',
        'Topic Tree',
        'manage_options',
        'topic-tree-analysis',
        'topic_tree_display_analysis',
        'dashicons-lightbulb',
        100
    );

    add_submenu_page(
        'topic-tree-analysis',
        'Topic Tree Settings',
        'Settings',
        'manage_options',
        'topic-tree-settings',
        'topic_tree_render_settings_page'
    );

    add_filter('submenu_file', function ($submenu_file) {
        global $plugin_page;
        if ($plugin_page === 'topic-tree-analysis') {
            return 'non_existent_file.php';
        }
        return $submenu_file;
    });
}
add_action('admin_menu', 'topic_tree_add_admin_menus');

//ANCHOR - Fixes navigation redirect after settings save to return to analysis page.
function topic_tree_fix_navigation()
{
    if (isset($_GET['page']) && $_GET['page'] === 'topic-tree-settings' && isset($_POST['option_page']) && $_POST['option_page'] === 'topic_tree_settings_group' && isset($_POST['submit']) && !isset($_GET['settings-updated'])) {
        wp_safe_redirect(admin_url('admin.php?page=topic-tree-analysis'));
        exit;
    }
}
add_action('admin_init', 'topic_tree_fix_navigation', 999);

//ANCHOR - Registers settings for the Topic Tree plugin, including merge content option.
function topic_tree_register_settings()
{
    register_setting('topic_tree_settings_group', 'topic_tree_merge_content', array(
        'type' => 'boolean',
        'default' => false,
        'sanitize_callback' => 'topic_tree_sanitize_checkbox',
    ));

    add_settings_section(
        'topic_tree_main_section',
        'General Settings',
        null,
        'topic-tree-settings'
    );

    add_settings_field(
        'topic_tree_merge_content',
        'Merge Posts and Pages',
        'topic_tree_merge_content_callback',
        'topic-tree-settings',
        'topic_tree_main_section'
    );
}
add_action('admin_init', 'topic_tree_register_settings');

//ANCHOR - Sanitizes checkbox input to ensure it returns a boolean value.
function topic_tree_sanitize_checkbox($value)
{
    $sanitized = ($value === 'on' || $value === true || $value === 1) ? true : false;
    return $sanitized;
}

//ANCHOR - Renders the merge content checkbox field in the settings page.
function topic_tree_merge_content_callback()
{
    $merge_content = get_option('topic_tree_merge_content', false);
    echo "<input type='checkbox' name='topic_tree_merge_content' " . checked($merge_content, true, false) . " />";
    echo "<p class='description'>Enable to merge all posts and pages into a single set of topic groups generated by AI, mixing posts and pages within each group.</p>";
}

//ANCHOR - Renders the Topic Tree settings page in the admin dashboard.
function topic_tree_render_settings_page()
{
    if (!current_user_can('manage_options')) {
        wp_die('Unauthorized access');
    }
    ?>
    <div class="wrap">
        <h1>Topic Tree Settings</h1>
        <form method="post" action="options.php">
            <?php
            settings_fields('topic_tree_settings_group');
            do_settings_sections('topic-tree-settings');
            submit_button();
            ?>
        </form>
    </div>
    <?php
}

//ANCHOR - Enqueues admin styles and scripts for the Topic Tree analysis page.
function topic_tree_enqueue_admin_styles($hook) {
    if ($hook === 'toplevel_page_topic-tree-analysis') {
        header('Cache-Control: public, max-age=3600');

        wp_enqueue_style('inter-font', 'https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap', [], null);
        $css_file = plugin_dir_path(__FILE__) . 'admin-style.css';
        $css_version = file_exists($css_file) ? filemtime($css_file) : '1.0';
        wp_enqueue_style('topic-tree-admin-style', plugin_dir_url(__FILE__) . 'admin-style.css', ['inter-font'], $css_version);

        wp_enqueue_script('jquery');
        $js_file = plugin_dir_path(__FILE__) . 'admin-script.js';
        $js_version = file_exists($js_file) ? filemtime($js_file) : '2.8.37'; // Updated to match plugin version
        wp_enqueue_script('topic-tree-admin-script', plugin_dir_url(__FILE__) . 'admin-script.js', ['jquery'], $js_version, true);

        wp_localize_script('topic-tree-admin-script', 'topicTreeAjax', [
            'ajax_url' => admin_url('admin-ajax.php'),
            'nonce' => wp_create_nonce('topic_tree_seo_nonce')
        ]);
    }
}
add_action('admin_enqueue_scripts', 'topic_tree_enqueue_admin_styles');

//ANCHOR - Retrieves the latest modified time of published posts or pages.
function topic_tree_get_latest_modified_time() {
    $query = new WP_Query([
        'post_type' => ['post', 'page'],
        'post_status' => 'publish',
        'posts_per_page' => 1,
        'orderby' => 'modified',
        'order' => 'DESC'
    ]);
    $latest = $query->have_posts() ? get_the_modified_time('U', $query->posts[0]) : 0;
    wp_reset_postdata();
    return $latest;
}

//ANCHOR - Invalidates cache when a post or page is updated.
function topic_tree_invalidate_on_post_update($post_id, $post, $update) {
    if ($post->post_status === 'publish' && in_array($post->post_type, ['post', 'page'])) {
        delete_transient('tt_last_modified');
    }
}
add_action('save_post', 'topic_tree_invalidate_on_post_update', 10, 3);

/**
 * Calculate token count for a post/page based on its content.
 * @param int    $post_id The ID of the post/page.
 * @param string $content The content to calculate tokens for.
 * @return int The calculated token count.
 */

//ANCHOR - Estimates token count for content and saves it to post meta.
 function topic_tree_calculate_token_count($post_id, $content) {
    if (empty($content)) {
        return 0; // Fallback if content is empty
    }
    // Rough estimate: 1 token ≈ 4 characters
    $token_count = ceil(strlen($content) / 4);
    // Save the token count to post meta
    update_post_meta($post_id, 'token_count', $token_count);
    return $token_count;
}

//ANCHOR - Displays the Topic Tree analysis page with summaries, groups, and stats.
function topic_tree_display_analysis()
{
    if (!current_user_can('manage_options')) {
        wp_die('Unauthorized access');
    }

    $start_time = microtime(true);
    $merge_content = get_option('topic_tree_merge_content', false);
    $force_refresh = isset($_GET['force_refresh']) && $_GET['force_refresh'] === 'true';

    $last_modified = get_transient('tt_last_modified');
    $current_modified = topic_tree_get_latest_modified_time();
    if ($last_modified === false || $current_modified > $last_modified || $force_refresh) {
        delete_transient('tt_content_post');
        delete_transient('tt_content_page');
        global $wpdb;
        $wpdb->query("DELETE FROM {$wpdb->options} WHERE option_name LIKE '_transient_tt_summary_%'");
        $wpdb->query("DELETE FROM {$wpdb->options} WHERE option_name LIKE '_transient_tt_grouped_%'");
        $wpdb->query("DELETE FROM {$wpdb->options} WHERE option_name LIKE '_transient_tt_overall_summary_%'");
        $wpdb->query("DELETE FROM {$wpdb->options} WHERE option_name LIKE '_transient_tt_html_grouped_%'");
        $wpdb->query("DELETE FROM {$wpdb->options} WHERE option_name LIKE '_transient_tt_seo_%'");
        $wpdb->query("DELETE FROM {$wpdb->options} WHERE option_name LIKE '_transient_tt_hybrid_insights_%'");
        $wpdb->query("DELETE FROM {$wpdb->options} WHERE option_name LIKE '_transient_tt_keywords_%'");
        $wpdb->query("DELETE FROM {$wpdb->postmeta} WHERE meta_key = 'token_count'");
        set_transient('tt_last_modified', $current_modified, WEEK_IN_SECONDS);
        $force_refresh = true;
    }

    $all_summaries = topic_tree_summarize_content($force_refresh);

    if (!is_array($all_summaries)) {
        wp_die('Error: Could not retrieve content summaries.');
    }

    $total_posts = count(array_filter($all_summaries, fn($item) => $item['type'] === 'post'));
    $total_pages = count(array_filter($all_summaries, fn($item) => $item['type'] === 'page'));
    $total_items = $total_posts + $total_pages;
    $total_api_calls = 0;
    $total_input_tokens = 0;
    $total_output_tokens = 0;
    $total_tokens = 0;
    $cache_hits = 0;
    $cache_opportunities = $total_items + 1;
    if ($merge_content && $total_items > 0) {
        $cache_opportunities += 1;
    }

    $cost_per_input_token_usd = 0.03 / 1000;
    $cost_per_output_token_usd = 0.06 / 1000;

    foreach ($all_summaries as &$item) {
        $summary_cache_key = 'tt_summary_' . md5(get_post_field('post_content', $item['id']));
        $tokens_data = get_transient($summary_cache_key . '_tokens') ?: ['input' => 0, 'output' => 0, 'total' => 0];
        $item['tokens'] = $tokens_data;
        $total_input_tokens += (int) ($tokens_data['input'] ?? 0);
        $total_output_tokens += (int) ($tokens_data['output'] ?? 0);
        $total_tokens += (int) ($tokens_data['total'] ?? 0);
        if (get_transient($summary_cache_key) !== false) {
            $cache_hits++;
        } else {
            $total_api_calls++;
        }
    }
    unset($item);

    $posts = array_filter($all_summaries, fn($item) => $item['type'] === 'post');
    $pages = array_filter($all_summaries, fn($item) => $item['type'] === 'page');
    $overall_summary = topic_tree_generate_overall_summary(
        array_map(fn($item) => (object) ['post_title' => $item['title'], 'post_content' => $item['summary']], $posts),
        array_map(fn($item) => (object) ['post_title' => $item['title'], 'post_content' => $item['summary']], $pages),
        $force_refresh
    );
    $overall_cache_key = 'tt_overall_summary_' . md5(implode('', array_map(function ($item) {
        return ($item['title'] ?: '') . ($item['summary'] ?: '');
    }, $all_summaries)));
    $overall_tokens = get_transient($overall_cache_key . '_tokens') ?: ['input' => 0, 'output' => 0, 'total' => 0];
    $total_input_tokens += (int) ($overall_tokens['input'] ?? 0);
    $total_output_tokens += (int) ($overall_tokens['output'] ?? 0);
    $total_tokens += (int) ($overall_tokens['total'] ?? 0);
    if (get_transient($overall_cache_key) !== false) {
        $cache_hits++;
    } else {
        $total_api_calls++;
    }

    $grouped_content = null;
    if ($merge_content && $total_items > 0) {
        $group_cache_key = 'tt_grouped_' . md5(json_encode($all_summaries) . 'content');
        if ($force_refresh) {
            delete_transient($group_cache_key);
            delete_transient($group_cache_key . '_tokens');
        }
        $cached_grouped = get_transient($group_cache_key);
        if ($cached_grouped !== false) {
            $cache_hits++;
            $grouped_content = $cached_grouped;
        } else {
            $grouped_content = topic_tree_extract_and_group_topics($all_summaries, 'content', $force_refresh);
            error_log("Set grouped content: " . (is_string($grouped_content) ? 'Success' : 'Failed'));
            $total_api_calls++;
        }
        $group_tokens = get_transient($group_cache_key . '_tokens') ?: ['input' => 0, 'output' => 0, 'total' => 0];
        $total_input_tokens += (int) ($group_tokens['input'] ?? 0);
        $total_output_tokens += (int) ($group_tokens['output'] ?? 0);
        $total_tokens += (int) ($group_tokens['total'] ?? 0);
    }

    $input_cost_usd = $total_input_tokens * $cost_per_input_token_usd;
    $output_cost_usd = $total_output_tokens * $cost_per_output_token_usd;
    global $total_cost_usd, $exchange_rates;
    $total_cost_usd = $input_cost_usd + $output_cost_usd;
    error_log("Total cost in display: Input Tokens=$total_input_tokens, Output Tokens=$total_output_tokens, Total=$total_tokens, Cost=$total_cost_usd");

    $currencies = ['USD', 'CAD', 'EUR', 'GBP', 'AUD', 'JPY', 'INR'];
    $exchange_rates = topic_tree_get_exchange_rates($total_cost_usd, $currencies, $cache_hits);

    $site_name = get_bloginfo('name');
    $recent_query = new WP_Query([
        'post_type' => ['post', 'page'],
        'post_status' => 'publish',
        'posts_per_page' => 1,
        'orderby' => 'modified',
        'order' => 'DESC',
    ]);
    $recent_item = $recent_query->have_posts() ? $recent_query->posts[0] : null;
    $recent_title = $recent_item ? $recent_item->post_title : 'None';
    $recent_date = $recent_item ? get_the_modified_date('F j, Y', $recent_item->ID) : 'N/A';
    $recent_url = $recent_item ? get_permalink($recent_item->ID) : '#';
    if ($recent_url && strpos($recent_url, 'http') !== 0) {
        $recent_url = home_url($recent_url);
    }
    wp_reset_postdata();

    $cache_hit_ratio = ($cache_opportunities > 0) ? ($cache_hits / $cache_opportunities) * 100 : 0;

    ?>
    <div class="wrap topic-tree">
        <button id="sidebar-toggle" class="sidebar-toggle-btn" style="display: none;">☰</button>
        <div class="left-panel">
            <div class="sidebar" id="sidebar">
                <button id="sidebar-close" class="sidebar-close-btn">×</button>
                <h2>Site Info</h2>
                <ul>
                    <li><strong>Site Name:</strong> <?php echo esc_html($site_name); ?></li>
                    <li><strong>Total Published Posts:</strong> <?php echo esc_html($total_posts); ?></li>
                    <li><strong>Total Published Pages:</strong> <?php echo esc_html($total_pages); ?></li>
                    <li><strong>Most Recently Edited:</strong> <a href="<?php echo esc_url($recent_url); ?>" target="_blank"
                            rel="noopener noreferrer"><?php echo esc_html($recent_title); ?></a>
                        <em>(<?php echo esc_html($recent_date); ?>)</em></li>
                    <li><strong>Total API Calls:</strong> <?php echo esc_html($total_api_calls); ?></li>
                    <li><strong>Cache Hit Ratio:</strong> <?php echo esc_html(number_format($cache_hit_ratio, 1)); ?>%</li>
                    <li><strong>Total Input Tokens:</strong> <?php echo esc_html(number_format($total_input_tokens)); ?></li>
                    <li><strong>Total Output Tokens:</strong> <?php echo esc_html(number_format($total_output_tokens)); ?></li>
                    <li><strong>Total Tokens Used:</strong> <?php echo esc_html(number_format($total_tokens)); ?></li>
                    <li>
                        <strong>Total Cost:</strong>
                        <select id="currency-selector">
                            <?php foreach ($currencies as $currency): ?>
                                <option value="<?php echo esc_attr($currency); ?>" <?php echo $currency === 'USD' ? 'selected' : ''; ?>>
                                    <?php echo esc_html($currency); ?>
                                </option>
                            <?php endforeach; ?>
                        </select>
                        <span id="total-cost-display">Loading...</span>
                    </li>
                </ul>
            </div>
            <div class="group-index-container" id="group-index-container">
                <h2><?php echo $merge_content ? 'Group Index' : 'All Content'; ?></h2>
                <?php
                if ($merge_content && $total_items > 0 && $grouped_content) {
                    // Grouped mode: Display group links
                    $decoded_groups = json_decode($grouped_content, true);
                    if ($decoded_groups && !empty($decoded_groups)) {
                        echo '<ul>';
                        foreach (array_keys($decoded_groups) as $group) {
                            $group_id = 'group-' . sanitize_title($group);
                            echo '<li><a href="#' . esc_attr($group_id) . '">' . esc_html($group) . '</a></li>';
                        }
                        echo '</ul>';
                    } else {
                        echo '<p>No groups available.</p>';
                    }
                } else {
                    // Flat list mode: Display links to all individual pages and posts
                    echo '<ul>';
                    $has_items = false;

                    // List all pages
                    if (!empty($pages)) {
                        foreach ($pages as $page) {
                            $title = isset($page['title']) ? $page['title'] : 'Untitled';
                            $post_id = isset($page['id']) ? $page['id'] : sanitize_title($title);
                            echo '<li><a href="#page-' . esc_attr($post_id) . '">[Page] ' . esc_html($title) . '</a></li>';
                            $has_items = true;
                        }
                    }

                    // List all posts
                    if (!empty($posts)) {
                        foreach ($posts as $post) {
                            $title = isset($post['title']) ? $post['title'] : 'Untitled';
                            $post_id = isset($post['id']) ? $post['id'] : sanitize_title($title);
                            echo '<li><a href="#post-' . esc_attr($post_id) . '">[Post] ' . esc_html($title) . '</a></li>';
                            $has_items = true;
                        }
                    }

                    // If no items, show a message
                    if (!$has_items) {
                        echo '<li>No content available.</li>';
                    }

                    echo '</ul>';
                }
                ?>
            </div>
        </div>
        <div class="main-content">
            <h1>Topic Tree Analysis</h1>
            <p class="description">Generated by GPT-4. <a
                    href="<?php echo esc_url(admin_url('admin.php?page=topic-tree-settings')); ?>">Adjust settings</a>.
                <a href="<?php echo esc_url(add_query_arg('force_refresh', 'true')); ?>">Force Refresh Token Counts</a>
            </p>

            <div class="section overall-summary">
                <h2>Overall Website Summary</h2>
                <p><?php echo esc_html($overall_summary); ?></p>
            </div>

            <?php if ($merge_content && $total_items > 0) { ?>
                <div class="section grouped-content">
                    <h2>Grouped Content (<?php echo esc_html($total_items); ?> items)</h2>
                    <?php
                    try {
                        echo topic_tree_render_grouped_content($grouped_content, $total_items);
                    } catch (Exception $e) {
                        echo '<p>Error: Failed to render grouped content.</p>';
                    }
                    ?>
                </div>
            <?php } else { ?>
                <div class="section pages-summary">
                    <h2>Pages (<?php echo esc_html($total_pages); ?>)</h2>
                    <?php echo topic_tree_render_summaries($pages, 'page'); ?>
                </div>
                <div class="section posts-summary">
                    <h2>Posts (<?php echo esc_html($total_posts); ?>)</h2>
                    <?php echo topic_tree_render_summaries($posts, 'post'); ?>
                </div>
            <?php } ?>

            <div class="keyword-analysis-wrap">
                <button id="analyze-keywords-btn" class="button button-primary">Analyze Keywords</button>
                <div id="keyword-analysis-output" style="display: none; margin-top: 20px; position: relative;">
                    <span id="keyword-analysis-close" class="keyword-analysis-close-btn">×</span>
                    <h2>Keyword Analysis</h2>
                    <?php foreach ($all_summaries as $item) { ?>
                        <div class="keyword-item">
                            <h3><?php echo esc_html($item['title']); ?> (<?php echo $item['type']; ?>)</h3>
                            <?php
                            // Skip analysis if content is too short (less than 10 words)
                            $word_count = $item['total_words'] ?? 0;
                            if ($word_count < 10) {
                                echo '<p>Content is too short for keyword analysis (minimum 10 words required).</p>';
                                continue;
                            }

                            $keywords = $item['keywords'] ?? [];
                            if (empty($keywords)) {
                                echo '<p>No significant keywords found (minimum 2 occurrences required).</p>';
                                continue;
                            }
                            ?>
                            <table class="wp-list-table widefat striped">
                                <thead>
                                    <tr>
                                        <th scope="col">Keyword</th>
                                        <th scope="col">Occurrences</th>
                                        <th scope="col">Density</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php
                                    // Sort keywords by count and density
                                    uasort($keywords, function($a, $b) {
                                        if ($a['count'] === $b['count']) {
                                            return $b['density'] <=> $a['density'];
                                        }
                                        return $b['count'] <=> $a['count'];
                                    });

                                    foreach ($keywords as $word => $data) {
                                        $density = $data['density'];
                                        $formatted_density = number_format($density, 1);

                                        // Determine row color based on density
                                        $row_style = '';
                                        if ($density >= 1 && $density <= 3) {
                                            // Ideal range: green
                                            $row_style = 'background-color: rgba(46, 204, 113, 0.2);';
                                        } elseif (($density >= 0.5 && $density < 1) || ($density > 3 && $density <= 3.5)) {
                                            // Within 0.5% of limits: yellow
                                            $row_style = 'background-color: rgba(241, 196, 15, 0.2);';
                                        } elseif ($density < 0.5) {
                                            // Too low: orange
                                            $row_style = 'background-color: rgba(243, 156, 18, 0.2);';
                                        } elseif ($density > 3.5) {
                                            // Too high: red
                                            $row_style = 'background-color: rgba(214, 54, 56, 0.2);';
                                        }
                                        ?>
                                        <tr style="<?php echo esc_attr($row_style); ?>">
                                            <td><?php echo esc_html($word); ?></td>
                                            <td><?php echo esc_html($data['count']); ?></td>
                                            <td><?php echo esc_html($formatted_density); ?>%</td>
                                        </tr>
                                        <?php
                                    }
                                    ?>
                                </tbody>
                            </table>
                            <?php
                            // High-density warning
                            $max_density = max(array_column($keywords, 'density'));
                            if ($max_density > 3) {
                                ?>
                                <p class="keyword-note" style="color: #d63638;">High density detected (<?php echo esc_html($max_density); ?>%)—check for over-optimization. Ideal density is 1-3%.</p>
                                <?php
                            }
                            ?>
                        </div>
                    <?php } ?>
                </div>
            </div>
        </div>
    </div>
    <?php
    echo "<!-- Rendered: " . (microtime(true) - $start_time) . "s -->";
}
add_action('admin_footer', 'topic_tree_add_sidebar_scripts');

//ANCHOR - Adds JavaScript for sidebar toggle functionality on the analysis page.
function topic_tree_add_sidebar_scripts() {
    if (!isset($_GET['page']) || $_GET['page'] !== 'topic-tree-analysis') {
        return;
    }
    ?>
    <script type="text/javascript">
        jQuery(document).ready(function($) {
            var $sidebar = $('#sidebar');
            var $mainContent = $('.main-content');
            var $closeBtn = $('#sidebar-close');
            var $toggleBtn = $('#sidebar-toggle');

            $closeBtn.on('click', function() {
                $sidebar.addClass('collapsed');
                $mainContent.addClass('full-width');
                $toggleBtn.show();
            });

            $toggleBtn.on('click', function() {
                $sidebar.removeClass('collapsed');
                $mainContent.removeClass('full-width');
                $toggleBtn.hide();
            });
        });
    </script>
    <?php
}

//ANCHOR - Fetches exchange rates for cost display, caching results for a day.
function topic_tree_get_exchange_rates($total_cost_usd, $currencies, &$cache_hits)
{
    $cache_key = 'tt_exchange_rates';
    $cached_rates = get_transient($cache_key);

    if ($cached_rates !== false) {
        $cache_hits++;
        return $cached_rates;
    }

    $api_url = 'https://v6.exchangerate-api.com/v6/015ced6f5ce3a1e42a6d2d54/latest/USD';
    $response = wp_remote_get($api_url, ['timeout' => 10]);

    if (is_wp_error($response)) {
        return topic_tree_fallback_exchange_rates($total_cost_usd, $currencies);
    }

    $body = json_decode(wp_remote_retrieve_body($response), true);
    if (!isset($body['conversion_rates'])) {
        return topic_tree_fallback_exchange_rates($total_cost_usd, $currencies);
    }

    $rates = [];
    $symbols = [
        'USD' => '$',
        'CAD' => 'C$',
        'EUR' => '€',
        'GBP' => '£',
        'AUD' => 'A$',
        'JPY' => '¥',
        'INR' => '₹'
    ];

    foreach ($currencies as $currency) {
        $rate = $body['conversion_rates'][$currency] ?? 1.0;
        $rates[$currency] = [
            'rate' => (float) $rate,
            'symbol' => $symbols[$currency] ?? $currency
        ];
    }

    set_transient($cache_key, $rates, DAY_IN_SECONDS);
    return $rates;
}

//ANCHOR - Provides fallback exchange rates if API call fails.
function topic_tree_fallback_exchange_rates($total_cost_usd, $currencies)
{
    $fallback_rates = [
        'USD' => 1.0,
        'CAD' => 1.35,
        'EUR' => 0.85,
        'GBP' => 0.75,
        'AUD' => 1.40,
        'JPY' => 110.0,
        'INR' => 75.0
    ];
    $symbols = [
        'USD' => '$',
        'CAD' => 'C$',
        'EUR' => '€',
        'GBP' => '£',
        'AUD' => 'A$',
        'JPY' => '¥',
        'INR' => '₹'
    ];

    $rates = [];
    foreach ($currencies as $currency) {
        $rates[$currency] = [
            'rate' => $fallback_rates[$currency] ?? 1.0,
            'symbol' => $symbols[$currency] ?? $currency
        ];
    }
    return $rates;
}

//ANCHOR - Renders grouped content into HTML with pagination and analysis buttons.
function topic_tree_render_grouped_content($grouped_content, $total_items) {
    if (!is_string($grouped_content)) {
        return '<p>Error: Invalid grouped content format.</p>';
    }

    $decoded = json_decode($grouped_content, true);
    if ($decoded === null) {
        return '<p>Error: Invalid JSON format in grouped content.</p>';
    }

    if (empty($decoded)) {
        return '<p>No topics generated.</p>';
    }

    $items_per_page = 10;
    $total_groups = count($decoded);
    $total_pages = ceil($total_groups / $items_per_page);
    $current_page = isset($_GET['tt_page']) ? max(1, intval($_GET['tt_page'])) : 1;
    $offset = ($current_page - 1) * $items_per_page;
    $paged_groups = array_slice($decoded, $offset, $items_per_page, true);

    $cache_key = 'tt_html_grouped_' . md5($grouped_content . $current_page);
    $cached_html = get_transient($cache_key);
    if ($cached_html !== false) {
        return $cached_html;
    }

    $output = '';
    foreach ($paged_groups as $category => $items) {
        if (!is_array($items)) {
            continue;
        }
        $item_count = count($items);
        $item_label = $item_count === 1 ? 'item' : 'items';
        $group_data = json_encode(['category' => $category, 'items' => $items, 'total_items' => $total_items]);
        $toggle_id = 'group-toggle-' . md5($category);
        $group_id = 'group-' . sanitize_title($category);

        $insights = "This content outlines the group of {$item_count} post items, constituting a portion of the site content, primarily revolving around the themes of {$category}. For a WordPress developer, this group is crucial as it represents a significant portion of the site’s content and focuses on contemporary design trends.";

        $output .= '<div class="group-card" id="' . esc_attr($group_id) . '">';
        $output .= '<h3>' . esc_html($category) . ' (' . esc_html($item_count) . ' ' . $item_label . ') ';
        $output .= '<button class="group-analyze-btn" data-group="' . esc_attr($group_data) . '">Show Group Info</button> ';
        $output .= '<button class="toggle-group-btn" data-toggle-id="' . esc_attr($toggle_id) . '">Expand All</button></h3>';

        $output .= '<div class="group-analysis">';
        $output .= '<h4>Group Summary & Importance</h4>';
        $output .= '<p>' . nl2br(esc_html($insights)) . '</p>';
        $output .= '</div>';

        $output .= '<ul class="group-content" id="' . esc_attr($toggle_id) . '">';
        foreach ($items as $index => $item) {
            $title = $item['title'] ?? 'Untitled';
            $summary = $item['summary'] ?? 'No summary'; // Use full summary directly
            $date = $item['date'] ?? 'Unknown Date';
            $type = $item['type'] ?? 'unknown';
            $url = $item['url'] ?? '#';
            if ($url !== '#' && strpos($url, 'http') !== 0) {
                $url = home_url($url);
            }
            $post_id = $item['id'] ?? 0;
            $edit_url = admin_url("post.php?post={$post_id}&action=edit");
            $item_json = esc_attr(json_encode($item));
            $tokens_data = $item['tokens'] ?? ['input' => 0, 'output' => 0, 'total' => 0];
            $tokens_data['input'] = (int)($tokens_data['input'] ?? 0);
            $tokens_data['output'] = (int)($tokens_data['output'] ?? 0);
            $tokens_data['total'] = (int)($tokens_data['total'] ?? 0);
            $token_count = $tokens_data['total'];

            // Debug: Log summary length
            error_log("Grouped Item {$post_id} Summary Length: " . strlen($summary) . " chars, Words: " . topic_tree_count_words($summary));

            $output .= '<li style="position: relative;">';
            if ($item['stale']) {
                $output .= '<div class="stale-mark">';
                $output .= 'Stale';
                $output .= '<span class="stale-tooltip">';
                $output .= 'Created over ' . esc_html($item['created_years']) . ' years ago, ';
                $output .= 'last edited ';
                if ($item['last_edited_years'] > 0) {
                    $output .= esc_html($item['last_edited_years']) . ' years';
                } else {
                    $output .= esc_html($item['last_edited_months']) . ' months';
                }
                $output .= ' ago, consider reviewing or refreshing it.';
                $output .= '</span>';
                $output .= '</div>';
            }
            $output .= '<div>';
            $output .= '<strong><a href="' . esc_url($url) . '" class="content-link" target="_blank" rel="noopener noreferrer">' . esc_html($title) . '</a></strong> ';
            $output .= '<button class="analyze-btn" data-item="' . $item_json . '">Analyze</button> ';
            $output .= '<a href="' . esc_url($edit_url) . '" class="edit-btn" target="_blank" rel="noopener noreferrer">Edit</a> ';
            $output .= '(' . esc_html($type) . ')';
            $output .= '</div>';
            $output .= '<div>' . esc_html($summary) . '</div>'; // Full summary, no truncation
            $output .= '<div><em>(' . esc_html($date) . ')</em></div>';
            $output .= '<div class="token-count">Tokens: Input: ' . esc_html(number_format($tokens_data['input'])) . ', Output: ' . esc_html(number_format($tokens_data['output'])) . ', Total: ' . esc_html(number_format($tokens_data['total'])) . '</div>';
            $output .= '<div class="seo-suggestions-inline" data-post-id="' . esc_attr($post_id) . '" style="display: none;"></div>';
            $output .= '</li>';
        }
        $output .= '</ul>';
        $output .= '</div>';
    }

    $output .= '<div class="pagination">';
    if ($current_page > 1) {
        $prev_page = $current_page - 1;
        $output .= '<a href="' . esc_url(add_query_arg('tt_page', $prev_page)) . '" class="pagination-link">Previous</a>';
    }
    $output .= '<span class="pagination-info">Page ' . esc_html($current_page) . ' of ' . esc_html($total_pages) . '</span>';
    if ($current_page < $total_pages) {
        $next_page = $current_page + 1;
        $output .= '<a href="' . esc_url(add_query_arg('tt_page', $next_page)) . '" class="pagination-link">Next</a>';
    }
    $output .= '</div>';

    $output = $output ?: '<p>No valid grouped content to display.</p>';
    set_transient($cache_key, $output, WEEK_IN_SECONDS);
    return $output;
}

function topic_tree_render_summaries($summaries, $type) {
    if (!is_array($summaries) || empty($summaries)) {
        return '<p>No ' . esc_html($type) . 's available.</p>';
    }

    $output = '<ul>';
    foreach ($summaries as $item) {
        $title = $item['title'] ?? 'Untitled';
        $summary = $item['summary'] ?? 'No summary';
        $url = $item['url'] ?? '#';
        if ($url !== '#' && strpos($url, 'http') !== 0) {
            $url = home_url($url);
        }
        $date = $item['date'] ?? 'Unknown Date';
        $type = $item['type'] ?? 'unknown';
        $post_id = $item['id'] ?? 0;
        $edit_url = admin_url("post.php?post={$post_id}&action=edit");
        $item_json = esc_attr(json_encode($item));
        // Try tokens['total'], fall back to transient directly
        $token_count = $item['tokens']['total'] ?? 0;
        $tokens_data = $item['tokens'] ?? ['input' => 0, 'output' => 0, 'total' => 0];
        // Ensure token values are numeric
        $tokens_data['input'] = isset($tokens_data['input']) ? (int)$tokens_data['input'] : 0;
        $tokens_data['output'] = isset($tokens_data['output']) ? (int)$tokens_data['output'] : 0;
        $tokens_data['total'] = isset($tokens_data['total']) ? (int)$tokens_data['total'] : 0;
        $token_count = $tokens_data['total'];
        if ($token_count === 0 && $post_id) {
            $content = get_post_field('post_content', $post_id);
            $summary_cache_key = 'tt_summary_' . md5($content);
            $tokens_data = get_transient($summary_cache_key . '_tokens') ?: ['input' => 0, 'output' => 0, 'total' => 0];
            // Ensure token values are numeric after fallback
            $tokens_data['input'] = isset($tokens_data['input']) ? (int)$tokens_data['input'] : 0;
            $tokens_data['output'] = isset($tokens_data['output']) ? (int)$tokens_data['output'] : 0;
            $tokens_data['total'] = isset($tokens_data['total']) ? (int)$tokens_data['total'] : 0;
            $token_count = $tokens_data['total'];
            error_log("Topic Tree: Fallback token count for $type ID $post_id - Total: $token_count");
        }

        // Add id attribute to each <li> for jump links in flat list mode
        $output .= '<li id="' . esc_attr($type . '-' . $post_id) . '" style="position: relative;">';
        if ($item['stale']) {
            $output .= '<div class="stale-mark">';
            $output .= 'Stale';
            $output .= '<span class="stale-tooltip">';
            $output .= 'Created over ' . esc_html($item['created_years']) . ' years ago, ';
            $output .= 'last edited ';
            if ($item['last_edited_years'] > 0) {
                $output .= esc_html($item['last_edited_years']) . ' years';
            } else {
                $output .= esc_html($item['last_edited_months']) . ' months';
            }
            $output .= ' ago, consider reviewing or refreshing it.';
            $output .= '</span>';
            $output .= '</div>';
        }
        $output .= '<div>';
        $output .= '<strong><a href="' . esc_url($url) . '" class="content-link" target="_blank" rel="noopener noreferrer">' . esc_html($title) . '</a></strong> ';
        $output .= '<button class="analyze-btn" data-item="' . $item_json . '">Analyze</button> ';
        $output .= '<a href="' . esc_url($edit_url) . '" class="edit-btn" target="_blank" rel="noopener noreferrer">Edit</a> ';
        $output .= '(' . esc_html($type) . ')';
        $output .= '</div>';
        $output .= '<div>' . esc_html($summary) . '</div>';
        $output .= '<div><em>(' . esc_html($date) . ')</em></div>';
        $output .= '<div class="token-count">Tokens: Input: ' . esc_html(number_format($tokens_data['input'])) . ', Output: ' . esc_html(number_format($tokens_data['output'])) . ', Total: ' . esc_html(number_format($tokens_data['total'])) . '</div>';
        $output .= '<div class="seo-suggestions-inline" data-post-id="' . esc_attr($post_id) . '" style="display: none;"></div>';
        $output .= '</li>';
    }
    $output .= '</ul>';
    return $output;
}

//ANCHOR Renders individual post or page summaries in a list format.
function topic_tree_fetch_seo_suggestions() {
    check_ajax_referer('topic_tree_seo_nonce', 'nonce');

    if (!current_user_can('manage_options')) {
        wp_send_json_error('Unauthorized access');
    }

    $item = isset($_POST['item']) ? json_decode(stripslashes($_POST['item']), true) : null;
    if (!$item || !is_array($item)) {
        wp_send_json_error('Invalid item data');
    }

    $item = array_map('sanitize_text_field', $item); // Sanitize input

    $suggestions = topic_tree_generate_seo_suggestions($item);
    if (!is_array($suggestions) || empty($suggestions)) {
        wp_send_json_error('Failed to generate SEO suggestions');
    }

    wp_send_json_success($suggestions);
}
add_action('wp_ajax_topic_tree_fetch_seo', 'topic_tree_fetch_seo_suggestions');

//ANCHOR Handles AJAX request to fetch currency data and recalculate costs.
function topic_tree_fetch_currency_data() {
    if (!check_ajax_referer('topic_tree_seo_nonce', 'nonce', false)) {
        wp_send_json_error('Invalid nonce');
        return;
    }
    if (!current_user_can('manage_options')) {
        wp_send_json_error('Unauthorized');
        return;
    }

    // Recalculate total cost based on cached token counts
    $posts = topic_tree_get_all_content('post', false);
    $pages = topic_tree_get_all_content('page', false);
    $total_input_tokens = 0;
    $total_output_tokens = 0;

    $cost_per_input_token_usd = 0.03 / 1000;
    $cost_per_output_token_usd = 0.06 / 1000;

    // Overall summary tokens
    $overall_cache_key = 'tt_overall_summary_' . md5(implode('', array_map(function ($p) {
        return ($p->post_title ?: '') . ($p->post_content ?: '');
    }, array_merge($posts, $pages))));
    $overall_tokens = get_transient($overall_cache_key . '_tokens') ?: ['input' => 0, 'output' => 0, 'total' => 0];
    $total_input_tokens += $overall_tokens['input'];
    $total_output_tokens += $overall_tokens['output'];
    error_log("Overall tokens: " . print_r($overall_tokens, true));

    // Individual post/page summary tokens
    foreach (array_merge($posts, $pages) as $p) {
        $summary_cache_key = 'tt_summary_' . md5($p->post_content ?: '');
        $tokens_data = get_transient($summary_cache_key . '_tokens') ?: ['input' => 0, 'output' => 0, 'total' => 0];
        $total_input_tokens += (int) ($tokens_data['input'] ?? 0);
        $total_output_tokens += (int) ($tokens_data['output'] ?? 0);
        error_log("Tokens for post {$p->ID}: " . print_r($tokens_data, true));
    }

    // Grouped content tokens (if merged)
    $merge_content = get_option('topic_tree_merge_content', false);
    if ($merge_content && count($posts) + count($pages) > 0) {
        $all_summaries = array_merge(
            array_map(function ($p) { return ['id' => $p->ID, 'summary' => get_transient('tt_summary_' . md5($p->post_content ?: ''))]; }, $posts),
            array_map(function ($p) { return ['id' => $p->ID, 'summary' => get_transient('tt_summary_' . md5($p->post_content ?: ''))]; }, $pages)
        );
        $group_cache_key = 'tt_grouped_' . md5(json_encode($all_summaries) . 'content');
        $tokens_data = get_transient($group_cache_key . '_tokens') ?: ['input' => 0, 'output' => 0, 'total' => 0];
        $total_input_tokens += (int) ($tokens_data['input'] ?? 0);
        $total_output_tokens += (int) ($tokens_data['output'] ?? 0);
        error_log("Grouped tokens in fetch: " . print_r($tokens_data, true));
    }

    $input_cost_usd = $total_input_tokens * $cost_per_input_token_usd;
    $output_cost_usd = $total_output_tokens * $cost_per_output_token_usd;
    $total_cost_usd = $input_cost_usd + $output_cost_usd;
    error_log("Total cost in fetch: Input Tokens=$total_input_tokens, Output Tokens=$total_output_tokens, Cost=$total_cost_usd");

    $currencies = ['USD', 'CAD', 'EUR', 'GBP', 'AUD', 'JPY', 'INR'];
    $cache_hits = 0;
    $exchange_rates = topic_tree_get_exchange_rates($total_cost_usd, $currencies, $cache_hits);

    wp_send_json_success([
        'exchangeRates' => $exchange_rates,
        'totalCostUsd' => $total_cost_usd
    ]);
}
add_action('wp_ajax_topic_tree_fetch_currency', 'topic_tree_fetch_currency_data');